### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by davidh-ssec** [pytroll/aggdraw#11]
Is this project still being maintained by you @jakul? Would it be possible to add some maintainers/collaborators to this project to continue making updates?

I'm sure @mraspaud and myself would be willing to help.

**Comment by jakul** [comment]
Hey @david-ssec.

Originally this repo was a fork of some other repo. I only made a small change (something like 2 lines) to allow it to compile on a different architecture. 

I'm happy to make you maintainers, but do not use or maintain this code myself. 

You may also want to consider /check for other newer forks of that original code base which may have more recent development activity (like https://github.com/preo/aggdraw). 

Craig.

**Comment by davidh-ssec** [comment]
FYI to anyone that finds this: We (PyTroll) are taking over maintainer-ship of this project for now. I am still trying to contact effbot about getting permission to the PyPI repository so that we can make updates to the package. If not, we may just make a new package name.

Leaving this open until the PyPI stuff can get resolved.

**Comment by a-hurst** [comment]
@davidh-ssec Sounds great! Commenting so I'll stay updated re: the PyPi status, because my interim solution of including this repo as a dependency link for pip/setuptools causes a lot of extra pain and confusion (e.g. aggdraw doesn't get installed when my package is installed as a dependency, meaning it has to be installed manually beforehand or else it will crash).

**Comment by davidh-ssec** [comment]
@a-hurst Understood.

Also if anyone has any other ideas or methods for contacting effbot (I won't use his real name here) let me know or point me to a resource or I'll let you know how to contact me if needed. I've tried to emails for one of his old companies (pythonware) and haven't gotten a response yet. Next thing I'm thinking of trying is making a support ticket on PyPI to have them contact him and/or transfer access to me/us.

**Comment by a-hurst** [comment]
@davidh-ssec Have you tried his LinkedIn? That's the most recent page online activity I can find for the guy. His old company also has a [contact page](http://www.pythonware.com/company/contact.htm) with an email that might be worth a shot. If that fails, hopefully PyPi will be receptive to the idea of new maintainers taking over an old package.

**Comment by davidh-ssec** [comment]
Tried the old company email (and his direct email for that company from a README file). For LinkedIn I would have to get a free trial or pay (I think) to contact him without being connected first. He also has no reason to "connect" with me so I assumed that he would ignore the invite. I can try that later.

**Comment by a-hurst** [comment]
Hi again @davidh-ssec, I'm assuming given the lack of updates in this thread there hasn't been any luck contacting effbot, so I just took a look at [PyPi's GitHub issue tracker](https://github.com/pypa/pypi-legacy/issues) and it looks like they tend to be receptive to package ownership requests and have a pretty good turnaround time for getting back to people. I'd make a request myself, but given that I'm not the one who wants PyPi ownership of the project it's probably better coming from you. 

Thanks again for keeping aggdraw actively maintained!

**Comment by davidh-ssec** [comment]
I was not aware of the github issue tracker. I had created an issue on the sourceforge repository with no luck. I just created a github issue, thanks for the info.

https://github.com/pypa/pypi-legacy/issues/714
