### ISSUE TITLE
Couldn't install, seems to be a problem with pathing to freetype

### ISSUE THREAD

**Issue by joepagan** [pytroll/aggdraw#2]
Ok so I moved all the files from my install of freetype from this directory `/usr/local/Cellar/freetype/2.5.3_1/include/freetype2` 
Put them in the folder `/Users/username/Downloads/aggdraw-master/agg2/font_freetype`
Then to install it on OSX `sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future easy_install /Users/username/Downloads/aggdraw-master`

**Comment by davidh-ssec** [comment]
This should be fixed/helped with recent changes in both distutils and the switch to using the `freetype-config` in setup.py.
