### ISSUE TITLE
Blank output image (v1.3)

### ISSUE THREAD

**Issue by bhbr** [pytroll/aggdraw#20]
The following MWE draws a square in version 1.1, but renders an empty image in version 1.3.
```python
import numpy as np
import aggdraw
from PIL import Image
from colour import Color

pixel_array = np.zeros((1080,1920,4))
image = Image.fromarray(pixel_array, mode = "RGBA")
canvas = aggdraw.Draw(image)

# path for a square
pathstring = "M825 405 C915 405 1005 405 1095 405 C1095 495 1095 585 1095 675 C1005 675 915 675 825 675 C825 585 825 495 825 405 Z"
symbol = aggdraw.Symbol(pathstring)
pen = aggdraw.Pen("#00ff00", 5)
fill = aggdraw.Brush("#ff0000", 127)

canvas.symbol((0, 0), symbol, pen, fill)
canvas.flush()

image2 = Image.fromarray(pixel_array, mode = "RGBA")

image2.show()
```

**Comment by davidh-ssec** [comment]
What version of python and what operating system? Thanks.

**Comment by bhbr** [comment]
python 2.7.14 on macOS Sierra

**Comment by davidh-ssec** [comment]
With the old version of aggdraw is this what the result looked like for you:

![image](https://user-images.githubusercontent.com/1828519/38369495-740ffe1c-38ad-11e8-80ee-aac701eade72.png)

**Comment by bhbr** [comment]
Yes

**Comment by davidh-ssec** [comment]
What if you don't use any alpha (RGB instead of RGBA)? I've been told by more experienced users (I just maintain the code) that aggdraw has always had less than ideal handling of alpha.

**Comment by bhbr** [comment]
Without alpha (I presume you mean making the array MxNx3 and mode = "RGB") the bug appears with both Python 2 and 3.

**Comment by davidh-ssec** [comment]
@bhbr I'm just not reviewing this code and I'm a little confused by what is happening. The way you are creating a Draw object, flushing it, then using the original pixel_array to make a new image, is this advertised/accepted behavior for `aggdraw`? Is the expectation that `pixel_array` will get written to in place? Or am I looking at this too early in the morning and misunderstanding something?

**Comment by burlito** [comment]
So what I think is happening is:

in static agg::rgba8 getcolor(PyObject* color, int opacity) https://github.com/pytroll/aggdraw/blob/master/aggdraw.cxx#L896

in `if` statement `PyBytes_Check(color)` was changed to `PyUnicode_Check(color)` which is false in situations where PyBytes_Check was true.

next even if you skip that PyObject* ascii_color = PyUnicode_AsASCIIString(color); will always give you NULL.

I don't think PyUnicode_Check and PyUnicode_AsASCIIString are used corectly in that file

**Comment by davidh-ssec** [comment]
Awesome @burlito thanks for the help. I agree it looks like I screwed up the python 2 support. There should be a second else if statement to check for the bytes.

For your second point, what do you mean PyUnicode_AsASCIIString will always return `NULL`? In both python 2 and 3 that should convert a *unicode* object to an ascii string if it can be converted (). As mentioned the code should have another if statement for bytes and then run `PyBytes_AsString(color)`. You are right that the `PyUnicode_AsASCIIString` will always return NULL for a bytes object (if it doesn't crash), but that function shouldn't be called in that case.

I'll see if I can find time to test this later.

**Comment by davidh-ssec** [comment]
I have this fixed locally, but it seems a test is failing on python 2 now and I can't get it to pass even after removing my changes. This should be fun.
