### ISSUE TITLE
1.3.1 core dumps in aggdraw.Pen() when run in xenial docker image

### ISSUE THREAD

**Issue by lsmithso** [pytroll/aggdraw#22]
aggdraw 1.3.1 core dumps when run in a Xenial docker image.  It works
fine with aggdraw 1.3 in a docker image, and both versions work find
when run natively.

I've isolated it to a call to aggdraw.Pen(). A docker image that
reproduces the problem is pasted below. Run it with
"gitlab-ci-multi-runner exec docker test".

image: ubuntu:xenial
test:
  script:
    - apt-get update 
    - apt-get -y install python-pip
    - pip install 'aggdraw==1.3.1' pillow
    - python -c "from PIL import Image;import aggdraw; main = Image.new('RGB', (480, 1024), 'white'); d = aggdraw.Draw(main); p = aggdraw.Pen((90,) * 3, 0.5)"

**Comment by davidh-ssec** [comment]
Good news I am able to reproduce this using an ubuntu xenial docker image (without gitlab runner). I'll see if I can figure this out today.

**Comment by lsmithso** [comment]
Hi: 1.3.2 works fine in docker and our tests now pass. Thanks much for
your swift fix.

David Hoese writes:
 > @lsmithso Version 1.3.2 is being built now. If all the tests pass this should result in a PyPI release: https://travis-ci.org/pytroll/aggdraw/builds/370571437
 > 
 > Let me know if this fixes things for you.
 > 
 > -- 
 > You are receiving this because you were mentioned.
 > Reply to this email directly or view it on GitHub:
 > https://github.com/pytroll/aggdraw/issues/22#issuecomment-383928589

-- 
Les Smithson
