### ISSUE TITLE
DOC: conda install has no freetype support on Windows

### ISSUE THREAD

**Issue by pllim** [pytroll/aggdraw#28]
Hello. I realized now that README recommends install from source for all platforms. However, by intuition, I first tried `conda install` (and also `pip install` at some point, I think). While it installed successfully on Windows, it did not have `freetype` support. To get that to work on Windows, I did this:

1. Clone the aggdraw repository.
2. Modify setup.py like mentioned in https://stackoverflow.com/questions/17770413/aggdraw-cannot-load-font-no-text-renderer
3. python setup.py install

I am documenting in here in case you wish to add a warning for Windows users. Thanks.

**Comment by djhoese** [comment]
Aggdraw from conda-forge is meant to have freetype support enabled/included. Could you do me a favor and try `freetype-config --prefix` from your conda environment?

Additionally that stackoverflow question is out of date as the `setup.py` is now meant to find freetype automatically using the command mentioned above which is here in the setup.py (https://github.com/pytroll/aggdraw/blob/master/setup.py#L39). What did you set yours too when you built it from source?

Lastly, how are you checking that freetype support is enabled?

**Comment by djhoese** [comment]
I just saw your linked issue for how it was failing. Maybe we need to add more output to the setup.py for what freetype it is using.

**Comment by djhoese** [comment]
Lastly, do you have freetype manually installed in your conda environment? It's possible that the conda-forge recipe is broken and needs to force freetype installation.

**Comment by pllim** [comment]
Thanks for following up, @djhoese ! Sorry for the late reply but looks like you have dug to the bottom of this. :+1:
