### ISSUE TITLE
Remove .svn directories

### ISSUE THREAD

**Issue by sebastic** [pytroll/aggdraw#47]
The source tree still contains the `.svn` directories, please remove them.
```
find . -type d -name ".svn" -exec git rm -rf {} \;
```

**Comment by djhoese** [comment]
These are for the bundled/embedded AGG2 library included with aggdraw. These are *not* our files. I'd be ok removing them, but I'm 90% sure this was an unpacked tarball taken straight from the AGG2 project.

**Comment by djhoese** [comment]
Nevermind, you are right. Seems like the original aggdraw author must have done an svn checkout.

**Comment by djhoese** [comment]
@sebastic Are these directories causing issues for you or does poor practice just drive you nuts? 😉

**Comment by sebastic** [comment]
Mostly for sanity. To ease the burden when reviewing the files in the tarball as part of the Debian packaging, these files were excluded from the repacked tarball we import in our packaging repository.

**Comment by djhoese** [comment]
Sounds good. Since it sounds like this is only affecting reviewing and not actual building, do you need a new release of aggdraw where these directories are removed?

**Comment by sebastic** [comment]
No release required, we'll be glad to see those directories gone in the next release whenever that happens.

This issue was actually triggered when I reviewed the changes between 1.3.7 we have in the package repo and the recent releases on master.
