### ISSUE TITLE
build error according to the readme badge

### ISSUE THREAD

**Issue by matkoniecz** [pytroll/aggdraw#51]

**Comment by djhoese** [comment]
Thanks for bringing this up @matkoniecz. I'm aware of the failures, but was unable to fix them. Last time I checked I was able to get them to pass by adding a blank line to the test configuration (something that shouldn't matter). I'll look in to it again.

**Comment by matkoniecz** [comment]
After https://github.com/pytroll/aggdraw/pull/52 it seems to be failing on evironment setup in https://travis-ci.org/pytroll/aggdraw/jobs/484934100

>     Uninstalling setuptools-18.2:
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The last command, `pip install --upgrade setuptools` is running without sudo unlike some earlier ones. And just yesterday my pip on my PC was freezing when it was missing both `sudo` and user install mode.

Maybe adding missing sudo will help?

**Comment by djhoese** [comment]
@matkoniecz Looks like you are right and cibuildwheels is aware of it: https://github.com/joerick/cibuildwheel/issues/122

This isn't something we can control though since it is happening in the cibuildwheels tool so we'll have to wait for someone to come up with and merge a fix on their side.
