### ISSUE TITLE
documentation has left the chat.

### ISSUE THREAD

**Issue by ahmed4end** [pytroll/aggdraw#71]
where is the decent documentation  i'm looking for ? where it is ? things should be more perfect than this !

**Comment by djhoese** [comment]
From the main github repository page:

![image](https://user-images.githubusercontent.com/1828519/102507284-acc03500-4049-11eb-9db6-29785b27b980.png)

There is a link to the right to https://aggdraw.readthedocs.io/en/latest/

This project and package were forked from the original aggdraw to keep it alive. The documentation was also adapted from that project. If you would like more information then I suggest a more constructive bug report with exactly the type of documentation you think is missing and what you would like added.

Your rudeness is not appreciated.
