### ISSUE TITLE
No arc symbols?

### ISSUE THREAD

**Issue by mike-lawrence** [pytroll/aggdraw#76]
The SVG spec apparently supports [specification of arcs](https://svg-path-visualizer.netlify.app), but when I try:

```python
pathstring = "M0,0 a .5 .5 0 0 1 1 0 z"
symbol = aggdraw.Symbol(pathstring)
```
I get the error:
```
ValueError: unknown path command 'A'
```
Am I doing something wrong, or does aggdraw not support arcs?

**Comment by djhoese** [comment]
According to the documentation `A` is not supported:

https://aggdraw.readthedocs.io/en/latest/#aggdraw.Symbol

This may be a limitation of the agg C library aggdraw is using underneath. I'm not quite sure. The `main` branch of this repository has a newer version of agg that it uses and may support this symbol (again, not sure), but we haven't released this version as the final output isn't the same in all cases. We/I don't have the time to dive in further for why there are differences and I haven't gotten any response from the agg maintainers for help.
