### ISSUE TITLE
is there a way to draw squircle (rectangle with rounded edges) ?

### ISSUE THREAD

**Issue by ahmed4end** [pytroll/aggdraw#77]

**Comment by djhoese** [comment]
Do you have more details on your question? For example...what is a squircle?

**Comment by ahmed4end** [comment]
@djhoese  squircle  is a rectangle with rounded edges

**Comment by djhoese** [comment]
This is not the answer you are looking for, but I don't think I (one of the maintainers of this project) know exactly. I've done the bare minimum to keep this library available, but don't actually know how to do most things with it. Here are the methods you can call from the Draw object:

https://github.com/pytroll/aggdraw/blob/bd751fc2e27554c06736fa0e2db55a6eb2ee87ac/aggdraw.cxx#L1735-L1750

So you can create a rectangle directly from this or you could use a Symbol to define an SVG element: https://aggdraw.readthedocs.io/en/latest/#aggdraw.Symbol
You could also look at the various Pen options for how the line joins should be done:
https://aggdraw.readthedocs.io/en/latest/#aggdraw.Pen

Last resort, you can define the exact line paths yourself.

Side note: I don't remember why, but the Draw methods aren't showing up in the docs, sorry.

**Comment by ahmed4end** [comment]
@djhoese cool, i will mess around with funcs to create it, thanks for keeping the awesome lib alive ♥
