### ISSUE TITLE
Windows binaries are missing for aggdraw 1.3.13 on pypi.org

### ISSUE THREAD

**Issue by m-khvoinitsky** [pytroll/aggdraw#82]

**Comment by djhoese** [comment]
We just switched to Github Actions for our wheel building and apparently I completely missed that #84 didn't include Windows wheels. @odidev Any time to add Windows to your wheel building jobs?

**Comment by djhoese** [comment]
I just started the builds for version 1.3.14 which should include the Windows wheels again. I'll update this issue when the release is on PyPI.

**Comment by djhoese** [comment]
Looks like Windows wheels are on PyPI now: https://pypi.org/project/aggdraw/

If you still find issues with it feel free to comment here and we can reopen the issue. Thanks for letting us know about this.

**Comment by m-khvoinitsky** [comment]
Thank you for quick fix!
